version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
      - ./libraries:/libraries  # Монтирование общей директории
    ports:
      - "28001:8000"